apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-config
  namespace: jenkins
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: https://student-app-control-plane:6443
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN... # KIND CA cert
      name: kind-student-app
    contexts:
    - context:
        cluster: kind-student-app
        user: kind-student-app
      name: kind-student-app
    current-context: kind-student-app
    preferences: {}
    users:
    - name: kind-student-app
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN... # KIND client cert
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlF... # KIND client key